version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    ports:
      - 8009:80
    environment:
      - DATABASE_URL=postgresql://ml-task-manager-prod:ml-task-manager-prod@db:5432/ml-task-manager-prod
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ml-task-manager-prod
      - POSTGRES_PASSWORD=ml-task-manager-prod
      - POSTGRES_DB=ml-task-manager-prod

volumes:
  postgres_data_prod:
