services:
  web:
    image: humblebeaver/ml-task-manager
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://ml-task-manager:ml-task-manager@db:5432/ml-task-manager
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ml-task-manager
      - POSTGRES_PASSWORD=ml-task-manager
      - POSTGRES_DB=ml-task-manager
  slurmmanager:
    image: managerslurm
    hostname: slurmmanager
    user: admin
    volumes:
      - shared-vol:/home/admin
  slurmmaster:
    image: masterslurm
    hostname: slurmmaster
    user: admin
    volumes:
      - shared-vol:/home/admin
    ports:
      - 6817:6817
      - 6818:6818
      - 6819:6819
  slurmnode1:
    image: nodeslurm
    hostname: slurmnode1
    user: admin
    volumes:
      - shared-vol:/home/admin
    links:
      - slurmmaster
  slurmnode2:
    image: nodeslurm
    hostname: slurmnode2
    user: admin
    volumes:
      - shared-vol:/home/admin
    links:
      - slurmmaster
  slurmnode3:
    image: nodeslurm
    hostname: slurmnode3
    user: admin
    volumes:
      - shared-vol:/home/admin
    links:
      - slurmmaster

volumes:
  postgres_data:
  shared-vol:
